GET http://localhost:4000/api/v1/participants
Accept: application/json

###
GET http://localhost:4000/api/v1/participants/1398
Accept: application/json

###
PUT http://localhost:4000/api/v1/participants/1398
Content-Type: application/json

{
    "name": "Prueba 2",
    "birthDate": "1990-01-01",
    "Curp": "ABCD900101HMCRLN02",
    "Photo": "new_photo.jpg",
    "Email": "jane.doe@example.com",
    "sex": "F"
}